image: node:16

pipelines:
  default:
    - step:
        name: Teste de API com Newman
        caches:
          - node
        script:
          - npm install -g newman
          - npm install
          - newman run collections/GoRest.postman_collection.json -e environments/GoRest.postman_environment.json
